<p>Use this form to add a new member to the membership list. <em>Items marked with a red asterisk (<font color=red>*</font>) are required.</em></p>

<center>

<table>

<form action=./ method=post>
<input type=hidden name=cmd value=add>

<tr>
<td align=center colspan=2 bgcolor=silver><b>Name</b></td>
</tr>

<tr>
<td align=right>First name<font color=red>*</font>:</td>
<td><input name=first_name></td>
</tr>

<tr>
<td align=right>Last name<font color=red>*</font>:</td>
<td><input name=last_name></td>
</tr>

<tr>
<td align=center colspan=2 bgcolor=silver><b>Addresses</b></td>
</tr>

<tr>
<td align=right>Email address<font color=red>*</font>:</td>
<td><input name=email></td>
</tr>

<tr>
<td align=right>Postal address 1<font color=red>*</font>:</td>
<td><input name=address_1></td>
</tr>

<tr>
<td align=right>Postal address 2:</td>
<td><input name=address_2></td>
</tr>

<tr>
<td align=right>City<font color=red>*</font>:</td>
<td><input name=city></td>
</tr>

<tr>
<td align=right>State<font color=red>*</font>:</td>
<td><input name=state value="NC"></td>
</tr>

<tr>
<td align=right>Zip code<font color=red>*</font>:</td>
<td><input name=zip_code></td>
</tr>

<tr>
<td align=right>Telephone<!-- font color=red>*</font -->:</td>
<td><input name=telephone></td>
</tr>

<tr>
<td align=center colspan=2 bgcolor=silver><b>Demographics</b></td>
</tr>

<tr>
<td align=right>Employer<!-- font color=red>*</font -->:</td>
<td><input name=employer></td>
</tr>

<tr>
<td align=right>Occupation<!-- font color=red>*</font -->:</td>
<td><input name=occupation></td>
</tr>

<tr>
<td align=right>Year of birth<!-- font color=red>*</font -->:</td>
<td><input name=birth_year></td>
</tr>

<tr>
<td></td>
<td><input type=submit name=submit value=Submit> <input type=reset><td>
</tr>

</form>

</table>

</center>
