<html>
<head>
<title>TriLUG membership list</title>
<style type="text/css">
    body {background-color: #ffffff;}
    div.c4 {text-align: center}
    a.c3 {font-family: arial, helvetica, sans-serif; font-size: 80%}
    td.c2 {font-family: arial, helvetica, sans-serif; font-size: 80%}
    span.c1 {font-family: arial, helvetica, sans-serif; font-size: 80%}
    code {font-family: monospace; }
</style>
</head>
<body>

<span class="c1">

<table cellpadding=10>

<tr valign=top>
<td valign="top" align="right" bgcolor="silver">
<center>
<a href="http://www.trilug.org/"><b>TriLUG</b></a><br>
<img src="./spacer.gif" alt="spacer" width="169" height="4" border="0">
</center><br>

<nobr>
<a href="./">Membership home</a><br /><br />
<a href="./?cmd=add">Add a member</a><br /><br />
<a href="./?cmd=displayall">List all members</a><br /><br />
<a href="./?cmd=search">Search the list</a><br /><br />
<a href="./?cmd=manual">Read the manual</a><br /><br /><br /><br />
<a href="./?cmd=emailall">Email membership to All</a><br /><br />
</nobr>

</td>

<td>
